const ACTION_TYPES = {
  PREVIEW_ADD_COMPONENT: 'PREVIEW_ADD_COMPONENT',
  PREVIEW_UPDATE_COMPONENT: 'PREVIEW_UPDATE_COMPONENT',
  PREVIEW_LOAD_COMPONENTS_FROM_EXTERNAL: 'PREVIEW_LOAD_COMPONENTS_FROM_EXTERNAL',
  PANEL_SHOW_PROPS: 'PANEL_SHOW_PROPS',
  PANEL_UPDATE_PROPS: 'PANEL_UPDATE_PROPS'
}

export default ACTION_TYPES